// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UploadFilesApi.Models;

public partial class Images
{
    public int Id { get; set; }

    public string Name { get; set; }

    public byte[] Data { get; set; }

    public string ContentType { get; set; }
}